### Задание 1.1

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [3]:
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

### Задание 1.2

In [4]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 1.3

In [5]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
a_centered_sp

8.0

In [6]:
a_centered_sp / (np.shape(a_centered)[0] - 1)

2.0

### Задание 1.4**

In [7]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

### Задание 2.1

In [8]:
import pandas as pd

In [9]:
authors = pd.DataFrame({
    "author_id": [1, 2, 3],
    "author_name": ["Тургенев", "Чехов", "Островский"]
})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [10]:
book = pd.DataFrame({
    "author_id": [1, 1, 1, 2, 2, 3, 3],
    "book_title": ["Отцы и дети", "Рудин", "Дворянское гнездо", "Толстый и тонкий", "Дама с собачкой", "Гроза", "Таланты и поклонники"], 
    "price": [450, 300, 350, 500, 450, 370, 290]
})
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Задание 2.2

In [11]:
authors_price = pd.merge(authors, book, on='author_id', how='outer')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Задание 2.3

In [12]:
top5 = authors_price.nlargest(5,'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

### Задание 2.4

In [13]:
authors_stat = authors_price.groupby("author_name")
authors_stat = authors_stat.agg(min_price=("price", min), max_price=("price", max), mean_price=("price", np.mean))
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

### Задание 2.5**

In [14]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [15]:
pd.pivot_table?

Signature:
pd.pivot_table(
    data: 'DataFrame',
    values=None,
    index=None,
    columns=None,
    aggfunc: 'AggFuncType' = 'mean',
    fill_value=None,
    margins=False,
    dropna=True,
    margins_name='All',
    observed=False,
    sort=True,
) -> 'DataFrame'
Docstring:
Create a spreadsheet-style pivot table as a DataFrame.

The levels in the pivot table will be stored in MultiIndex objects
(hierarchical indexes) on the index and columns of the result DataFrame.

Parameters
----------
data : DataFrame
values : column to aggregate, optional
index : column, Grouper, array, or list of the previous
    If an array is passed, it must be the same length as the data. The
    list can contain any of the other types (except list).
    Keys to group by on the pivot table index.  If an array is passed,
    it is being used as the same manner as column values.
columns : column, Grouper, array, or list of the previous
    If an array is passed, it must be the same length as the data. The

In [16]:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'],columns=['cover'], 
                           aggfunc=np.sum, fill_value=0)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [17]:
pd.DataFrame.to_pickle(book_info, "book_info.pkl")

In [18]:
book_info2 = pd.read_pickle("book_info.pkl")
book_info2

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950